server:
  port: 8080

spring:
  resources:
    static-locations:
  datasource:
    url: jdbc:mysql://localhost:3306/look?useUnicode=true&charcterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 127705
    driver-class-name: com.mysql.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://139.186.200.79:8809/look?useUnicode=true&charcterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: look
#    password: MChCrRMzECk526ms

#    driver-class-name: com.mysql.jdbc.Driver

#  quartz:
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: always

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:

mybatis:
  type-aliases-package: com.iswust.model
  mapper-locations: classpath:mapper/*.xml

file:
  ###静态资源对外暴露的访问路径
  staticAccessPath: /file/
  ###静态资源实际存储路径
  uploadFolder: E:/ResourceServer/
  uploadImage: image/
  uploadReportImage: reportImage/
  ###敏感文本
  sensitiveContent: E:/ResourceServer/SensitiveWord.txt
  ###静态资源访问前缀
  prefix: jp-tyo-dvm-2.sakurafrp.com:27063m

myRedis:
  ###每天的推荐最大值
  dayRange: 50
  ###每周的推荐最大值
  weekRange: 30
  ###推荐数
  recommendNum: 10
  ###热门数
  hotNum: 10
  ###全部最新数
  allLatestNum: 50
  ###话题最新数
  themeLatestNum: 100