server:
  prot:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/look?useUnicode=true&charcterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 127705
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.iswust.model
  mapper-locations: classpath:mapper/*.xml

file:
  ###静态资源对外暴露的访问路径
  staticAccessPath: /file/**
  ###静态资源实际存储路径
  uploadFolder: E:/ResourceServer/
  uploadImage: image/
  ###敏感文本
  sensitiveContent: E:/ResourceServer/SensitiveWord.txt
  ###静态资源访问前缀
  prefix: jp-tyo-dvm-2.sakurafrp.com:64091