server:
  prot:7070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/look?useUnicode=true&charcterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 127705
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.iswust.model
  mapper-locations: classpath:mapper/*.xml
